services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      # Menggunakan port yang tidak umum untuk menghindari konflik
      - "5433:5432"
    volumes:
      # Menyimpan data database agar tidak hilang
      - postgres-data:/var/lib/postgresql/data

  nextjs:
    build: 
    ports:
      # Aplikasi akan diakses di http://localhost:8080
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    # PERINTAH KUNCI: Tunggu database siap sebelum memulai aplikasi
    command: ["/usr/local/bin/wait-for-it", "postgres:5432", "--", "npm", "run", "dev"]

volumes:
  postgres-data: